import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Oh studio clone app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
          {children}
          <Navbar />
      </body>
    </html>
  );
}
